[web]
listen = ":81"

[mq]
conn = "amqp://ows:thingple@127.0.0.1:5672/"
[mq.subscribe]
whEvent = "wh_events_test"

[db]
user = "ows"
password = "thingple"
host = "127.0.0.1"
port = 5432
database = "wms"
ssl = "disable" #require/verify-full/verify-ca/disable
